
stages:
  - tex

compile_pdf:
  stage: tex
  tags:
    - latex
  script:
    - cd tex
    - latexmk -silent -f -pdf -bibtex -pdflatex="pdflatex -synctex=1 -interaction=nonstopmode %O %S" "master-thesis-peters.tex" || true
    - latexmk -silent -f -pdf -bibtex -pdflatex="pdflatex -synctex=1 -interaction=nonstopmode %O %S" "master-thesis-peters.tex"
    - curl -k -T master-thesis-peters.pdf -u "${NC_FILE_DROP}" -H "X-Requested-With: XMLHttpRequest" ${NC_URL}/master-thesis-peters.pdf
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    expire_in: 1 week
    paths:
      - tex/master-thesis-peters.pdf
