
stages:
  - tex

compile_pdf:
  stage: tex
  tags:
    - latex
  script:
    - cd tex
    - latexmk -pdf -silent -pdflatex="pdflatex -synctex=1  -interaction=nonstopmode %O %S" "master-thesis-peters.tex"
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    expire_in: 1 week
    paths:
      - tex/master-thesis-peters.pdf
